# Use a Node.js base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate database migrations
RUN npm run db:generate

# Expose the port
EXPOSE 3333

# Command to run the application
CMD ["npm", "run", "dev"]